# Travis-CI Build for OpenRA/ra2
# see travis-ci.org for details

language: csharp
mono: 4.6.1
sudo: false

cache:
  directories:
  - ~/.openra/Content

addons:
  apt:
    packages:
    - liblua5.1-0
    - p7zip-full
    - nsis
    - nsis-common

script:
 - make
 - . mod.config;
   if [ "${TRAVIS_TEST_MOD}" == "True" ]; then make test || travis_terminate 1; fi;
   if [ "${TRAVIS_TEST_PACKAGING}" == "True" ]; then ./packaging/package-all.sh test-0 || travis_terminate 1; fi
# Crashes, see https://github.com/OpenRA/OpenRA/issues/14013
# - make check

branches:
  only:
    - master

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true

before_deploy:
 - mkdir build
 - cd build && ../packaging/package-all.sh ${TRAVIS_TAG} ${PWD} && cd ..
 - . mod.config

deploy:
  provider: releases
  api_key: ${GH_DEPLOY_API_KEY}
  file:
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}.exe
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}-macOS.zip
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}-winportable.zip
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}.AppImage
  skip_cleanup: true
  on:
    tags: true
